sudo: false

language: php

branches:
  except:
    - /^release-.*$/
    - /^ghgfk-.*$/

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - zf-mkdoc-theme

env:
  global:
    - SITE_URL: https://zendframework.github.io/zend-config
    - GH_USER_NAME: "Matthew Weier O'Phinney"
    - GH_USER_EMAIL: matthew@weierophinney.net
    - GH_REF: github.com/zendframework/zend-config.git
    - secure: "jx8uWYQ+9AizRVN4c+zWAT0plgTNcpYIJmvJ36dr0bZuGBb3PU4zd8vhqsNcd+q4f+pdeCM5u6gPTq8oUsmziQk4Ie9OvHMwdVIA1HhOvnjo4DvC2knqFeU97oguUS+lpl0eq5abGZMf+NrhzpIBjlAVSFGNYkAmCIKBRUjfFxigam65KKJ2gk1UUwPU6ozJ1z9WXeNZ5vDgXtdnMOur6ijWZ4jL81BP7h/daF/U64K8ZrajrL4qhwD58n56pHIXFmODUgwOnZofGWQ8iAmtpzR1cP0/KA3fUqpRNha6Hd9BScZizjoE/qcQgu3JuCqpqinLXFZbInhUE5O3qU5lHcokgnnOzotudI7ytbe+XTy+UH5p7RaW3l1LgNmoCc6/VxT5b/fXfxNp3V/dXZhu4br73bixA/oV8Fnatti4jRm+za5QdwGtwCp59+eWkz/AUhGXR/vc4Hq9l0EXUS1zMBBvBXrnYMQFp1GYErY6+HIH8rAruueoAxy3yEigL9BnIiA06j5teuf0iCdNtJystbCrCiGRXa/RAnzJoZxa+Kp+A0O+Gbgrz9LnQ0uYRCMxdBXMZRlbqHgi0usj/mfGtr8rnEB2NRNvMo2uYbJv6QJo71Ql5BgRD3OdKUzjj5N3+to90fa+PT6JrVy+FW+I4Qc0VAmJnJ3ggxW0puo//eI="

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - EXECUTE_CS_CHECK=true
    - php: 5.5
      env:
        - SERVICE_MANAGER_VERSION='^2.7.5'
    - php: 5.6
      env:
        - EXECUTE_TEST_COVERALLS=true
        - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
        - PATH="$HOME/.local/bin:$PATH"
    - php: 5.6
      env:
        - SERVICE_MANAGER_VERSION='^2.7.5'
    - php: 7
    - php: 7
      env:
        - SERVICE_MANAGER_VERSION='^2.7.5'
    - php: hhvm
    - php: hhvm
      env:
        - SERVICE_MANAGER_VERSION='^2.7.5'
  allow_failures:
    - php: hhvm

notifications:
  irc: "irc.freenode.org#zftalk.dev"
  email: false

before_install:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls ; fi
  - if [[ $SERVICE_MANAGER_VERSION != '' ]]; then composer require --dev --no-update "zendframework/zend-servicemanager:$SERVICE_MANAGER_VERSION" ; fi
  - if [[ $SERVICE_MANAGER_VERSION == '' ]]; then composer require --dev --no-update "zendframework/zend-servicemanager:^3.0.3" ; fi

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover clover.xml ; fi
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then ./vendor/bin/phpunit ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run ; fi
  - if [[ $DEPLOY_DOCS == "true" && "$TRAVIS_TEST_RESULT" == "0" ]]; then wget -O theme-installer.sh "https://raw.githubusercontent.com/zendframework/zf-mkdoc-theme/master/theme-installer.sh" ; chmod 755 theme-installer.sh ; ./theme-installer.sh ; fi

after_success:
  - if [[ $DEPLOY_DOCS == "true" ]]; then echo "Preparing to build and deploy documentation" ; ./zf-mkdoc-theme/deploy.sh ; echo "Completed deploying documentation" ; fi

after_script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/coveralls ; fi
